const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={hid:1,data:null,view:'dashboard'};
const fmt=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:(state.data?.households.find(h=>h.id==state.hid)?.currency||'EUR')}).format(Number(n||0));
const api=async(path,opt={})=>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});const j=await r.json();if(!r.ok) throw new Error(j.error||'Request failed');return j};
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
async function load(){state.data=await api('/api/bootstrap?household_id='+state.hid);renderHouseholds();render();}
function renderHouseholds(){const s=$('#householdSelect');s.innerHTML=state.data.households.map(h=>`<option value="${h.id}" ${h.id==state.hid?'selected':''}>${esc(h.name)}</option>`).join('')+`<option value="new">＋ New household</option>`;}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function avatar(m){return `<div class="avatar" style="background:${m.color||'#6c63ff'}">${esc(m.name[0])}</div>`}
function activeMembers(){return state.data.members.filter(m=>m.active)}
function monthExpenses(){let now=new Date();return state.data.expenses.filter(e=>{let d=new Date(e.expense_date+'T00:00:00');return d.getMonth()==now.getMonth()&&d.getFullYear()==now.getFullYear()})}
function dueState(e){if(!e.due_date)return ''; let d=new Date(e.due_date+'T23:59:59'),n=new Date();if(d<n)return 'overdue'; if((d-n)/86400000<5)return 'upcoming';return ''}
function navTitle(view){return {dashboard:['Good morning 👋','Here’s where your household stands this month.'],expenses:['Expenses','Add, edit, search and review shared spending.'],calendar:['Calendar','Upcoming bills and overdue items at a glance.'],settle:['Settle up','Reduce the group balance to the fewest transfers possible.'],members:['Household members','Manage the people sharing expenses.'],history:['History','A complete trail of expenses and repayments.'],settings:['Settings','Profile, preferences and protected bank details.']}[view]}
function render(){let [t,s]=navTitle(state.view);$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view)); const f={dashboard:dashboard,expenses:expensesView,calendar:calendarView,settle:settleView,members:membersView,history:historyView,settings:settingsView}[state.view];f();}
function dashboard(){const ex=monthExpenses();const total=ex.reduce((a,e)=>a+e.amount,0);const overdue=state.data.expenses.filter(e=>dueState(e)==='overdue').length;const upcoming=state.data.expenses.filter(e=>dueState(e)==='upcoming').length;const plan=state.data.settlement_plan;const mem=activeMembers();
$('#content').innerHTML=`<div class="grid-4"><div class="stat-card"><div class="stat-label">Spent this month</div><div class="stat-value">${fmt(total)}</div><div class="stat-foot">Across ${ex.length} expenses</div></div><div class="stat-card"><div class="stat-label">Transfers needed</div><div class="stat-value">${plan.length}</div><div class="stat-foot">Optimized settlement plan</div></div><div class="stat-card"><div class="stat-label">Upcoming payments</div><div class="stat-value">${upcoming}</div><div class="stat-foot">Due within 5 days</div></div><div class="stat-card"><div class="stat-label">Overdue</div><div class="stat-value ${overdue?'negative':''}">${overdue}</div><div class="stat-foot">Needs attention</div></div></div>
<div class="dashboard-grid"><div class="card"><h3>Who owes what</h3>${mem.map(m=>{let b=state.data.balances[m.id]||0;return `<div class="member-row">${avatar(m)}<div class="row-main"><strong>${esc(m.name)}</strong><small>${b>0?'is owed money':b<0?'owes the household':'is settled up'}</small></div><div class="amount ${b>0?'positive':b<0?'negative':''}">${b>0?'+':''}${fmt(b)}</div></div>`}).join('')}</div>
<div class="card"><h3>Next payments</h3>${state.data.expenses.filter(e=>e.due_date).sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(-6).map(e=>`<div class="expense-row"><div class="row-main"><strong>${esc(e.title)}</strong><small>${e.due_date}</small></div><span class="pill ${dueState(e)}">${dueState(e)||'scheduled'}</span><div class="amount">${fmt(e.amount)}</div></div>`).join('')||'<div class="empty">No scheduled payments.</div>'}</div></div>
<div class="two-col" style="margin-top:18px"><div class="card"><h3>Smart settlement preview</h3>${plan.slice(0,3).map(t=>`<div class="settle-row"><strong>${esc(t.from_name)}</strong><span class="transfer-arrow">→</span><strong>${esc(t.to_name)}</strong><div class="row-main"></div><div class="amount">${fmt(t.amount)}</div></div>`).join('')||'<div class="empty">Everyone is settled 🎉</div>'}</div><div class="card"><h3>Monthly breakdown</h3>${categoryBreakdown(ex)}</div></div>`}
function categoryBreakdown(ex){let o={};ex.forEach(e=>o[e.category]=(o[e.category]||0)+e.amount);let max=Math.max(1,...Object.values(o));return Object.entries(o).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div style="margin:13px 0"><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:6px"><b>${esc(k)}</b><span>${fmt(v)}</span></div><div class="progress"><span style="width:${v/max*100}%"></span></div></div>`).join('')||'<div class="empty">No spending this month.</div>'}
function expensesView(){const cats=['All','Rent','Groceries','Utilities','Internet','Entertainment','Other'];$('#content').innerHTML=`<div class="card"><div class="toolbar"><input id="search" placeholder="Search expenses…"><select id="catFilter">${cats.map(c=>`<option>${c}</option>`).join('')}</select><select id="statusFilter"><option>All statuses</option><option>Overdue</option><option>Upcoming</option></select></div><div id="expenseList"></div></div><div class="card" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center"><h3>Recurring expenses</h3><button class="secondary" id="addRecurring">＋ Add recurring</button></div>${state.data.recurring.map(r=>`<div class="expense-row"><div class="row-main"><strong>${esc(r.title)}</strong><small>Every month on day ${r.day_of_month} · paid by ${esc(r.payer_name)}</small></div><span class="pill">${esc(r.category)}</span><div class="amount">${fmt(r.amount)}</div></div>`).join('')||'<div class="empty">No recurring expenses yet.</div>'}</div>`;const draw=()=>{let q=$('#search').value.toLowerCase(),c=$('#catFilter').value,s=$('#statusFilter').value;let es=state.data.expenses.filter(e=>(e.title+' '+(e.note||'')).toLowerCase().includes(q)&&(c==='All'||e.category===c)&&(s==='All statuses'||dueState(e)===s.toLowerCase()));$('#expenseList').innerHTML=es.map(expenseRow).join('')||'<div class="empty">No matching expenses.</div>'};['search','catFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener('input',draw));draw();$('#addRecurring').onclick=openRecurring}
function expenseRow(e){return `<div class="expense-row"><div class="row-main"><strong>${esc(e.title)}</strong><small>${e.expense_date} · ${esc(e.category)} · paid by ${esc(e.payer_name)}${e.note?' · '+esc(e.note):''}</small></div>${dueState(e)?`<span class="pill ${dueState(e)}">${dueState(e)}</span>`:''}<div class="amount">${fmt(e.amount)}</div><button class="icon-btn" onclick="editExpense(${e.id})">✎</button><button class="icon-btn danger" onclick="deleteExpense(${e.id})">×</button></div>`}
function calendarView(){let now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];let cells=[];for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let iso=d.toISOString().slice(0,10);let ev=state.data.expenses.filter(e=>e.due_date===iso);cells.push(`<div class="day ${d.getMonth()!==m?'dim':''}"><div class="day-number">${d.getDate()}</div>${ev.map(e=>`<div class="event ${dueState(e)}" title="${esc(e.title)}">${esc(e.title)} · ${fmt(e.amount)}</div>`).join('')}</div>`)}$('#content').innerHTML=`<div class="card"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px"><h3>${now.toLocaleString('en',{month:'long'})} ${y}</h3><div><span class="pill overdue">overdue</span> <span class="pill upcoming">due soon</span></div></div><div class="calendar-wrap">${days.map(d=>`<div class="day-label">${d}</div>`).join('')}${cells.join('')}</div></div>`}
function settleView(){let p=state.data.settlement_plan;$('#content').innerHTML=`<div class="settle-hero"><h2>${p.length?`${p.length} transfer${p.length>1?'s':''} settles the whole house`:'Everyone is settled up 🎉'}</h2><div>Instead of everyone paying everyone else, HouseSplit works from each person’s net balance and removes unnecessary transfers.</div></div><div class="card"><h3>Optimized transfers</h3>${p.map((t,i)=>`<div class="settle-row">${avatar(state.data.members.find(m=>m.id===t.from_id))}<div class="row-main"><strong>${esc(t.from_name)} <span class="transfer-arrow">→</span> ${esc(t.to_name)}</strong><small>Transfer ${i+1} of ${p.length}</small></div><div class="amount">${fmt(t.amount)}</div><button class="primary" onclick="markPaid(${t.from_id},${t.to_id},${t.amount})">Mark paid</button></div>`).join('')||'<div class="empty">Nothing to pay.</div>'}</div>`}
function membersView(){let ms=state.data.members;$('#content').innerHTML=`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><h3>People in this household</h3><button class="primary" id="addMember">＋ Add member</button></div>${ms.map(m=>`<div class="member-row" style="opacity:${m.active?1:.45}">${avatar(m)}<div class="row-main"><strong>${esc(m.name)}</strong><small>${esc(m.email||'No email')} · ${m.active?'Active':'Removed'}</small></div>${m.active?`<button class="secondary danger" onclick="removeMember(${m.id})">Remove</button>`:''}</div>`).join('')}</div>`;$('#addMember').onclick=openMember}
function historyView(){let items=[...state.data.expenses.map(e=>({date:e.expense_date,type:'Expense',text:`${e.payer_name} paid ${e.title}`,amount:e.amount})),...state.data.settlements.map(s=>({date:s.paid_at.slice(0,10),type:'Settlement',text:`${s.from_name} paid ${s.to_name}`,amount:s.amount}))].sort((a,b)=>b.date.localeCompare(a.date));$('#content').innerHTML=`<div class="card"><h3>Activity history</h3>${items.map(i=>`<div class="history-row"><span class="pill">${i.type}</span><div class="row-main"><strong>${esc(i.text)}</strong><small>${i.date}</small></div><div class="amount">${fmt(i.amount)}</div></div>`).join('')}</div>`}
async function settingsView(){let s=await api('/api/settings?household_id='+state.hid);$('#content').innerHTML=`<div class="card" style="max-width:760px"><div class="secure-box">🔐 Bank details are encrypted before being stored. In production, keep encryption keys outside the application and use HTTPS, authentication, audit logs and a payment provider rather than storing raw banking credentials.</div><form id="settingsForm" class="form-grid"><label>Name<input name="owner_name" value="${esc(s.owner_name||'')}"></label><label>Email<input name="email" type="email" value="${esc(s.email||'')}"></label><label>Preferred currency<select name="preferred_currency"><option>EUR</option><option>USD</option><option>GBP</option></select></label><label>Bank name<input name="bank_name" value="${esc(s.bank_name||'')}"></label><label class="full">IBAN<input name="iban" value="${esc(s.iban||'')}" placeholder="e.g. ES12 3456 7890 …"></label><label class="full">Account holder<input name="account_holder" value="${esc(s.account_holder||'')}"></label><label class="full"><span><input name="notifications" type="checkbox" ${s.notifications?'checked':''}> Enable simple due-date notifications</span></label><div class="full actions"><button class="primary">Save settings</button></div></form></div>`;$('#settingsForm').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.household_id=state.hid;o.notifications=e.target.notifications.checked;await api('/api/settings',{method:'POST',body:JSON.stringify(o)});toast('Settings saved securely')};}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function openExpense(){let ms=activeMembers();modal('Add expense',`<form id="expenseForm" class="form-grid"><label class="full">Expense name<input name="title" required placeholder="e.g. September rent"></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Category<select name="category"><option>Rent</option><option>Groceries</option><option>Utilities</option><option>Internet</option><option>Entertainment</option><option>Other</option></select></label><label>Date<input name="expense_date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Due date<input name="due_date" type="date"></label><label>Who paid?<select name="payer_id">${ms.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><label class="full">Note<textarea name="note" placeholder="Optional note"></textarea></label><div class="full"><b style="font-size:12px">Split equally between</b><div class="check-list" style="margin-top:8px">${ms.map(m=>`<label class="check-item"><input type="checkbox" name="participant" value="${m.id}" checked>${esc(m.name)}</label>`).join('')}</div></div><div class="full actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Add expense</button></div></form>`);$('#expenseForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),o=Object.fromEntries(f);let parts=f.getAll('participant').map(Number);if(!parts.length)return toast('Select at least one person');let amount=Number(o.amount),base=Math.floor(amount/parts.length*100)/100,shares=parts.map((id,i)=>({member_id:id,share:i===parts.length-1?+(amount-base*(parts.length-1)).toFixed(2):base}));o.household_id=state.hid;o.splits=shares;await api('/api/expenses',{method:'POST',body:JSON.stringify(o)});closeModal();toast('Expense added');await load()}}
function openMember(){modal('Add household member',`<form id="memberForm" class="form-grid"><label class="full">Name<input name="name" required></label><label class="full">Email<input name="email" type="email"></label><label>Profile color<input name="color" type="color" value="#6c63ff"></label><div class="full actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Add member</button></div></form>`);$('#memberForm').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.household_id=state.hid;await api('/api/members',{method:'POST',body:JSON.stringify(o)});closeModal();toast('Member added');await load()}}
function openRecurring(){let ms=activeMembers();modal('Add recurring expense',`<form id="recForm" class="form-grid"><label class="full">Name<input name="title" required></label><label>Amount<input name="amount" type="number" step="0.01" required></label><label>Category<select name="category"><option>Rent</option><option>Utilities</option><option>Internet</option><option>Groceries</option><option>Other</option></select></label><label>Paid by<select name="payer_id">${ms.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><label>Day of month<input name="day_of_month" type="number" min="1" max="28" value="1"></label><label class="full">Note<input name="note"></label><div class="full actions"><button class="primary">Save recurring</button></div></form>`);$('#recForm').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.household_id=state.hid;await api('/api/recurring',{method:'POST',body:JSON.stringify(o)});closeModal();toast('Recurring expense saved');await load()}}
function editExpense(id){
  let e=state.data.expenses.find(x=>x.id===id),ms=activeMembers(),selected=new Set(e.splits.map(s=>s.member_id));
  modal('Edit expense',`<form id="editExpenseForm" class="form-grid"><label class="full">Expense name<input name="title" required value="${esc(e.title)}"></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required value="${e.amount}"></label><label>Category<select name="category">${['Rent','Groceries','Utilities','Internet','Entertainment','Other'].map(c=>`<option ${c===e.category?'selected':''}>${c}</option>`).join('')}</select></label><label>Date<input name="expense_date" type="date" required value="${e.expense_date}"></label><label>Due date<input name="due_date" type="date" value="${e.due_date||''}"></label><label>Who paid?<select name="payer_id">${ms.map(m=>`<option value="${m.id}" ${m.id===e.payer_id?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label><label class="full">Note<textarea name="note">${esc(e.note||'')}</textarea></label><div class="full"><b style="font-size:12px">Split equally between</b><div class="check-list" style="margin-top:8px">${ms.map(m=>`<label class="check-item"><input type="checkbox" name="participant" value="${m.id}" ${selected.has(m.id)?'checked':''}>${esc(m.name)}</label>`).join('')}</div></div><div class="full actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save changes</button></div></form>`);
  $('#editExpenseForm').onsubmit=async ev=>{ev.preventDefault();let f=new FormData(ev.target),o=Object.fromEntries(f),parts=f.getAll('participant').map(Number);if(!parts.length)return toast('Select at least one person');let amount=Number(o.amount),base=Math.floor(amount/parts.length*100)/100;o.splits=parts.map((mid,i)=>({member_id:mid,share:i===parts.length-1?+(amount-base*(parts.length-1)).toFixed(2):base}));await api('/api/expenses/'+id,{method:'PUT',body:JSON.stringify(o)});closeModal();toast('Expense updated');await load()}
}
async function deleteExpense(id){if(!confirm('Delete this expense?'))return;await api('/api/expenses/'+id,{method:'DELETE'});toast('Expense deleted');await load()}
async function removeMember(id){if(!confirm('Remove this member from future expense splitting? Existing history stays intact.'))return;await api('/api/members/'+id,{method:'DELETE'});toast('Member removed');await load()}
async function markPaid(a,b,amount){await api('/api/settlements',{method:'POST',body:JSON.stringify({household_id:state.hid,from_member_id:a,to_member_id:b,amount})});toast('Payment marked as settled');await load()}
async function newHousehold(){modal('Create household',`<form id="houseForm" class="form-grid"><label class="full">Household name<input name="name" placeholder="e.g. Madrid Flat" required></label><label>Currency<select name="currency"><option>EUR</option><option>USD</option><option>GBP</option></select></label><div class="full actions"><button class="primary">Create</button></div></form>`);$('#houseForm').onsubmit=async e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));let r=await api('/api/households',{method:'POST',body:JSON.stringify(o)});state.hid=r.id;closeModal();await load();toast('Household created')}}
$('#nav').onclick=e=>{let b=e.target.closest('button');if(!b)return;state.view=b.dataset.view;render()};$('.sidebar-bottom button').onclick=()=>{state.view='settings';render()};$('#addExpenseTop').onclick=openExpense;$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#householdSelect').onchange=e=>{if(e.target.value==='new')newHousehold();else{state.hid=+e.target.value;load()}};
load();
